Repository CMU-313/fall-22-hw4-team-sweg, pull requests merged in 2022-10, with the labels that each got.

#4 Add CI pipeline
  .github/workflows/main.yaml
Labels: build

#5 Add `pull_request_template.md`
  .github/workflows/pull_request_template.md
Labels: documentation

#15 Add `POST /models/:id/predict` swagger
  .github/pull_request_template.md
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  Pipfile
  Pipfile.lock
  README.md
  app/.flaskenv
  app/app.py
  app/dtos/__init__.py
  app/dtos/applicant.py
  app/dtos/prediction.py
  app/handlers/__init__.py
  app/handlers/models.py
Labels: documentation, build

#16 Add `POST /models`
  .github/workflows/ci.yaml
  app/dtos/__init__.py
  app/dtos/model_metadata.py
  app/dtos/train.py
  app/handlers/models.py
Labels: feature

#17 Add `POST /models/:id/predict` test
  .github/workflows/ci.yaml
  app/dtos/__init__.py
  app/dtos/applicant.py
  app/dtos/model_metadata.py
  app/dtos/prediction.py
  app/dtos/train.py
  app/handlers/models.py
  app/services/__init__.py
  app/services/model_service.py
  app/tests/test_models.py
  app/tests/test_placeholder.py
Labels: test

#18 Add test for training model
  .github/workflows/ci.yaml
  .github/workflows/main.yaml
  app/dtos/__init__.py
  app/dtos/train.py
  app/handlers/models.py
  app/services/model_service.py
  app/tests/test_models.py
Labels: test
