Repository CMU-313/fall-22-hw4-team-sweg, pull requests merged in 2022-11, with the labels that each got.

#22 Add `GET /models/{mode_id}`
  app/handlers/models.py
  app/tests/test_models.py
Labels: documentation, feature

#26 Preprocess dataset and select features
  app/dtos/model_metadata.py
  app/handlers/models.py
  app/services/model_service.py
  app/tests/test_models.py
  data/preprocess.py
  data/student-mat-preprocessed.csv
Labels: feature

#28 Cache feature rankings
  app/dtos/model_metadata.py
  app/handlers/models.py
  app/services/model_service.py
  app/tests/test_models.py
  data/preprocess.py
  data/ranked-features-chi2.txt
  data/ranked-features-f_classif.txt
  data/ranked-features-f_regression.txt
  data/ranked-features-mutual_info_classif.txt
  data/ranked-features-mutual_info_regression.txt
Labels: performance

#30 Implement model training functions and exporting metadata
  app/dtos/model_metadata.py
  app/handlers/models.py
  app/services/model_service.py
  app/tests/test_models.py
Labels: feature

#33 Add features readme
  README.md
  app/services/model_service.py
  data/features/ranked-features-mutual_info_classif.txt
  data/features/ranked-features-mutual_info_regression.txt
  data/models/20bf1dfd-291d-4b12-96a4-af29bf227780.pkl
  data/models/20bf1dfd-291d-4b12-96a4-af29bf227780.txt
  data/models/f1acd0b2-2a7c-43c0-9db7-ff0b0a2491fa.pkl
  data/models/f1acd0b2-2a7c-43c0-9db7-ff0b0a2491fa.txt
  docs/linear.png
  docs/logistic.png
Labels: documentation

#35 Implement get_model()
  app/services/model_service.py
  app/tests/test_models.py
Labels: feature

#44 Implement delete model
  app/services/model_service.py
Labels: feature

#45 Update `README.md`
  README.md
Labels: documentation
